S02 us23 admin add members
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #100
Opened 2022-11-03 09:48 UTC by williambouet

2022-11-03 10:10 UTC, toomanyMG submitted a review, later dismissed

2022-11-03 10:28 UTC, teddyandria submitted a review, later dismissed

2022-11-03 10:38 UTC, toomanyMG approved these changes

2022-11-03 16:23 UTC, sblondeau requested changes

2022-11-03 16:23 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +                $errorsUpload = $this->verifUpload($extension);
tu as 4 if imbriqués, c'est pas super :p 
déjà dans verifUpload, passe lui $_FILES['photo'] et non $extension
en fait comme pour $_POST, $_FILES le mieux c'est de le stocker dans une variable au début et de ne plus le manipuler direct

2022-11-03 16:23 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +                $errorsUpload = $this->verifUpload($extension);
tu as 4 if imbriqués, c'est pas super :p 
déjà dans verifUpload, passe lui $_FILES['photo'] et non $extension
en fait comme pour $_POST, $_FILES le mieux c'est de le stocker dans une variable au début et de ne plus le manipuler direct

2022-11-03 16:23 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +                if (empty($errorsUpload)) {
tu peux le sortir du if précédent (évite d'imbriquer les if si pas nécesaire)

2022-11-03 16:23 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +                    $errors = array_merge($errorsUpload, $errors);
ça tu peux le faire à la fin quand tu aurait récup $errors, c'est juste pour l'affichage

2022-11-03 16:23 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +            }
je comprends pas trop ton str_replace
mais dans tous les cas si tu as fais la quete retour vers le futur, passe par un object datetime et la méthode getLastErrors()

2022-11-03 16:23 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +    private function checkDateOfBirth(array $date): bool
à enlever/modifier avec Datetime (voir message plus haut)

2022-11-03 16:23 UTC, sblondeau commented on src/View/Admin/membersAdd.html.twig
> +							<form action="" method="post" enctype="multipart/form-data">
faire un fichier include pour pouvoir réutiliser le form

2022-11-03 16:23 UTC, sblondeau commented on src/View/Admin/membersAdd.html.twig
> +$('.datepicker').datepicker({format: 'd.mm.yyyy'});
?? tu mais un input type date ! tu auras un datepicker natif ;-)

2022-11-03 18:16 UTC, williambouet commented on src/Controller/AdminMemberController.php
> +                $errorsUpload = $this->verifUpload($extension);
Je sais pour les 4 if, mais je ne vois pas comment faire autrement pour sécuriser les étapes. Je suis comme le demande la quête. Je suis preneur d'une meilleure méthode.

2022-11-03 18:19 UTC, williambouet commented on src/Controller/AdminMemberController.php
> +                if (empty($errorsUpload)) {
bien vu

2022-11-04 09:49 UTC, teddyandria approved these changes

2022-11-04 12:49 UTC, shvilaine submitted a review, later dismissed

2022-11-04 14:29 UTC, teddyandria approved these changes

2022-11-04 14:29 UTC, shvilaine approved these changes

2022-11-04 16:17 UTC, sblondeau approved these changes

2022-11-04 16:17 UTC, merged