S02us12 detail route
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #102
Opened 2022-11-03 16:25 UTC by toomanyMG

2022-11-03 16:27 UTC, shvilaine approved these changes

2022-11-03 17:37 UTC, williambouet approved these changes

2022-11-04 07:56 UTC, sblondeau requested changes

2022-11-04 07:56 UTC, sblondeau commented on src/Controller/RouteController.php
> +        $routeid = $itemRouteManager->selectOneById($id);
c'est un tableau $route et non juste un $routeId que tu récupères, donc nomme le $route et dans ton twig c'est route.id si tu veux l'id et pas routeid.id

2022-11-04 07:56 UTC, sblondeau commented on public/assets/css/DetailRoute.css
> +	-webkit-transform: scale(1);
inultile le -webkit

2022-11-04 07:56 UTC, sblondeau commented on public/assets/css/DetailRoute.css
> +	-webkit-transition: .3s ease-in-out;
idem

2022-11-04 07:56 UTC, sblondeau commented on public/assets/css/DetailRoute.css
> +	-webkit-transform: scale(0.9);
et encore

2022-11-04 09:49 UTC, teddyandria approved these changes

2022-11-04 14:49 UTC, williambouet approved these changes

2022-11-07 08:47 UTC, sblondeau requested changes

2022-11-07 08:47 UTC, sblondeau commented on src/View/DetailRoute/DetailRoute.html.twig
> +		<h1 class="display-4 fw-bold text-danger text-center py-5">DETAILS DE LA SORTIE PASSEE</h1>
DÉTAILS
À VENIR
=> accents sur les majuscule
une bonne astuce c'est d'écrire en minuscule et de forcer la majuscule soit en twig avec le filtre |upper, soit en css avec text-transform

2022-11-07 08:47 UTC, sblondeau commented on src/View/DetailRoute/DetailRoute.html.twig
> +					<img src="../../assets/images/default.svg" {# replace memberid.img#} class="w-25 rounded-circle memberpic" alt="{# replace memberid.alt #}"/>
pourquoi ces commentaires partout ? 
tu es pas sensé boucler là plutot d'ailleurs ?
et pas la peine de faire ../../assets, normalent /assets suffit :o

2022-11-07 08:47 UTC, sblondeau commented on src/View/DetailRoute/DetailRoute.html.twig
> +			{# Call the photo table#}
tu dois le faire  cet appel à la table photo

2022-11-07 08:47 UTC, sblondeau commented on src/View/DetailRoute/DetailRoute.html.twig
> +			{# Call the photo table#}
tu dois tout appeler dynamiquement, après tu as beaucoup de code là, tu peux aussi découper ta pages en plusieurs sections, une US par section

2022-11-07 22:54 UTC, toomanyMG commented on src/View/DetailRoute/DetailRoute.html.twig
> +			{# Call the photo table#}
Pour le coup la table photo sera créer avec la page pour éditer une sortie vu que la section est accessible uniquement quand la sortie est passée.

2022-11-08 12:46 UTC, williambouet approved these changes

2022-11-09 07:56 UTC, sblondeau approved these changes

2022-11-09 07:56 UTC, merged