S02 us15 routelist admin
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #112
Opened 2022-11-04 09:34 UTC by teddyandria

2022-11-04 15:07 UTC, shvilaine submitted a review, later dismissed

2022-11-04 15:10 UTC, toomanyMG submitted a review, later dismissed

2022-11-07 08:48 UTC, sblondeau requested changes

2022-11-07 08:48 UTC, sblondeau commented on src/Controller/AdminRouteController.php
> +        $routemanager = new RouteManager();
routeManager (camelCase)

2022-11-07 08:48 UTC, sblondeau commented on src/View/AdminRoute/adminRoute.html.twig
> +				<h1 class="AdminRouteTitle text-danger text-center fs-1 mt-5">Administration des sorties</h1>
admin-route-title (pour le coup c'est une autre syntaxe préconisée pour les nom de classe css ;-))

2022-11-08 09:49 UTC, toomanyMG approved these changes

2022-11-08 10:52 UTC, williambouet approved these changes

2022-11-08 12:47 UTC, sblondeau approved these changes

2022-11-08 12:47 UTC, merged