fix update role value
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #124
Opened 2022-11-08 15:42 UTC by williambouet

2022-11-08 15:45 UTC, toomanyMG submitted a review, later dismissed

2022-11-09 08:14 UTC, teddyandria submitted a review, later dismissed

2022-11-09 09:29 UTC, sblondeau requested changes

2022-11-09 09:29 UTC, sblondeau commented on src/View/Admin/members.html.twig
> +								<td>{{ roles[member.role] }}</td>
tu peux accéder direct à une constante depuis Twig sinon, c'est peut etre plus adapté dans ton cas ?
https://twig.symfony.com/doc/3.x/functions/constant.html

2022-11-09 13:23 UTC, toomanyMG approved these changes

2022-11-09 13:33 UTC, shvilaine approved these changes

2022-11-09 14:11 UTC, merged