FIXS02US24 - fixed routes names for actualities
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #131
Opened 2022-11-09 15:08 UTC by shvilaine

2022-11-09 15:10 UTC, toomanyMG approved these changes

2022-11-09 15:13 UTC, williambouet approved these changes

2022-11-09 15:30 UTC, toomanyMG approved these changes

2022-11-09 16:04 UTC, williambouet approved these changes

2022-11-09 16:45 UTC, sblondeau requested changes

2022-11-09 16:45 UTC, sblondeau commented on src/routes.php
> +    'admin/actualites/edit' => ['AdminActuController', 'edit', ['id']],
edit add et delete c'est pas du français non plus ^^

et deleteRoute plus bas

2022-11-14 09:06 UTC, shvilaine commented
All of my links have been modified, but not those which are part of my colleagues' work (to not cause too many conflicts at one).

2022-11-14 09:56 UTC, williambouet approved these changes

2022-11-14 09:57 UTC, toomanyMG approved these changes

2022-11-14 10:09 UTC, sblondeau approved these changes

2022-11-14 10:09 UTC, merged