S02 us05 register table
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #143
Opened 2022-11-10 11:12 UTC by teddyandria

2022-11-10 11:21 UTC, shvilaine approved these changes

2022-11-10 19:36 UTC, williambouet approved these changes

2022-11-13 23:10 UTC, toomanyMG approved these changes

2022-11-14 07:56 UTC, williambouet approved these changes

2022-11-14 08:36 UTC, sblondeau requested changes

2022-11-14 08:36 UTC, sblondeau commented on src/Controller/RouteController.php
> +        $photos = $registerManager->selectByRouteId($id);
y a un truc qui va pas, tu sélectionne des route via un $id, puis des "Register" (je sais pas trop ce que c'est, les inscriptions à une sortie ?) via le **meme** $id ? tu peux tout faire via une seule jointure non ?

2022-11-14 08:36 UTC, sblondeau commented on src/Model/RegisterManager.php
> +        $statement = $this->pdo->prepare("SELECT photo FROM " . MemberManager::TABLE . " AS m
ah ok je comprend mieux là, mais c'est pas très logique
en fait tu devrais faire une seule requete depuis RouteManager qui devrait etre selectAllRegistration($id)
avec une double jointure.
Dans tous les cas si tu avait à garder un id de route ici, tu devrais le renommer $idRoute sinon on penserait que c'est un id de register

2022-11-14 12:54 UTC, toomanyMG submitted a review, later dismissed

2022-11-14 16:17 UTC, williambouet submitted a review, later dismissed

2022-11-14 16:19 UTC, toomanyMG submitted a review, later dismissed

2022-11-14 22:55 UTC, sblondeau approved these changes

2022-11-14 22:56 UTC, merged