delete admin link
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #163
Opened 2022-11-15 19:40 UTC by williambouet

2022-11-15 21:18 UTC, teddyandria approved these changes

2022-11-16 05:13 UTC, toomanyMG approved these changes

2022-11-16 08:47 UTC, sblondeau requested changes

2022-11-16 08:47 UTC, sblondeau commented on src/View/_footer.html.twig
> -			{% else %}
autant tu n'es pas forcé d'ajouter le lien vers l'admin sur la page d'accueil, autant tu dois quand meme garder la possiblité de se delogué (ou alors tu mets le bouton deconnexion uniquement coté admin)

2022-11-16 08:49 UTC, williambouet commented on src/View/_footer.html.twig
> -			{% else %}
on se délogue dans la navbar

2022-11-16 08:57 UTC, sblondeau approved these changes

2022-11-16 08:57 UTC, merged