fixed date time format
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #164
Opened 2022-11-15 19:46 UTC by williambouet

2022-11-15 21:18 UTC, teddyandria submitted a review, later dismissed

2022-11-16 05:13 UTC, toomanyMG approved these changes

2022-11-16 08:49 UTC, sblondeau requested changes

2022-11-16 08:49 UTC, sblondeau commented on src/View/List/listRoute.html.twig
> +									<div class="row justify-content-center pt-2 tool-font fs-4 pb-4">{{route.time|date('H:i')}}</div>
si je suis pointilleux, en français les dates s'écrivent 'd/m/Y' 
d'ailleur en bdd vous pourriez pas plutot avoir juste un datetime plutot que date ET time ?

2022-11-16 09:51 UTC, williambouet commented on src/View/List/listRoute.html.twig
> +									<div class="row justify-content-center pt-2 tool-font fs-4 pb-4">{{route.time|date('H:i')}}</div>
j'ai changé le format de la date pour être frenchy ;-)
en ce qui concerne la BDD, j'échange avec Mikaël pour qu'il te fasse un fix de son côté.
Peux tu valider stp.

2022-11-16 15:57 UTC, shvilaine approved these changes

2022-11-16 16:01 UTC, toomanyMG approved these changes

2022-11-16 16:33 UTC, sblondeau approved these changes

2022-11-16 16:33 UTC, merged