Initialisation
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #43
Opened 2022-10-24 14:22 UTC by williambouet

2022-10-24 15:10 UTC, toomanyMG approved these changes

2022-10-24 15:16 UTC, toomanyMG approved these changes

2022-10-24 15:19 UTC, teddyandria submitted a review, later dismissed

2022-10-25 08:54 UTC, sblondeau requested changes

2022-10-25 08:54 UTC, sblondeau commented on database.sql
> +IF NOT EXISTS CREATE DATABASE papys45;
déjà géré dans le fichier migration.php, inutile

2022-10-25 08:54 UTC, sblondeau commented on public/assets/css/style.css
> +    --spacing: 8px;
pas forcément utile de définir des spacing si tu utilises bootstrap, car tu as déjà plein de classes pour gérer les espacement

2022-10-25 08:54 UTC, sblondeau commented on src/View/layout.html.twig
> +	<head>
tu as un pb de tabulation. 1 tab doit etre config pour faire 4 espaces dans ton IDE, sinon tu vas reformater tous les fichiers à chaque fois

2022-10-25 09:38 UTC, closed without merging