S01 us06 route table
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #62
Opened 2022-10-28 09:21 UTC by toomanyMG

2022-10-28 09:22 UTC, williambouet submitted a review, later dismissed

2022-10-28 09:25 UTC, teddyandria approved these changes

2022-10-28 10:15 UTC, Zakari-B requested changes

2022-10-28 10:15 UTC, Zakari-B commented on src/View/List/listRoute.html.twig
> +						<div class="container text-center">
C'est un doublon accidentel du container ?

2022-10-28 10:19 UTC, williambouet submitted a review, later dismissed

2022-10-28 10:19 UTC, shvilaine approved these changes

2022-10-28 10:23 UTC, toomanyMG commented on src/View/List/listRoute.html.twig
> +						<div class="container text-center">
C'était bien accidentel.

2022-10-28 10:23 UTC, teddyandria approved these changes

2022-10-28 10:59 UTC, sblondeau requested changes
- fichier ds_store push
- les autres icones devraient aussi etre en svg, pas en png

2022-10-28 10:59 UTC, sblondeau commented on public/assets/css/list-route.css
> +    filter: invert(40%) sepia(91%) saturate(374%) hue-rotate(100deg) brightness(87%) contrast(92%);
non faut utiliser fill je pense et des variables de couleur

2022-10-28 11:12 UTC, toomanyMG commented on public/assets/css/list-route.css
> +    filter: invert(40%) sepia(91%) saturate(374%) hue-rotate(100deg) brightness(87%) contrast(92%);
Fill ne fonctionne pas x)

2022-10-29 08:40 UTC, williambouet approved these changes

2022-10-30 08:24 UTC, closed without merging