S02 us10 members
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #68
Opened 2022-10-29 18:42 UTC by williambouet

2022-11-01 09:45 UTC, toomanyMG submitted a review, later dismissed

2022-11-01 10:44 UTC, teddyandria submitted a review, later dismissed

2022-11-02 08:34 UTC, toomanyMG submitted a review, later dismissed

2022-11-02 08:34 UTC, teddyandria submitted a review, later dismissed

2022-11-02 08:36 UTC, sblondeau requested changes
les images de Roger et Serge n'ont pas à etre dans assets/images

2022-11-02 08:36 UTC, sblondeau commented on src/Controller/MembersController.php
> +class MembersController extends AbstractController
MemberController
MemberManager
Toujours au singulier !!!

2022-11-02 08:36 UTC, sblondeau commented on src/View/Members/index.html.twig
> +						{% if member.role is not empty and member.role is not same as 'activeMember' %}
tu dois pouvoir faire plus simple et moins répétitif, pour éliminer le if notamment
regarde https://twig.symfony.com/doc/2.x/filters/filter.html
on en reparle si tu n'y arrives pas ;-)

2022-11-02 08:36 UTC, sblondeau commented on src/View/Members/index.html.twig
> +								<img src="/assets/images/{{member.photo}}" class="card-img-top d-flex rounded-circle " alt="photo d'un membre actif">
et le code de la card est le meme les 2 fois. On pourrait sans doute faire une boucle imbriquée, mais si tu veux conserver 2 boucles, passe le code html de la card dans un fichier séparé que tu vas include

2022-11-02 11:00 UTC, toomanyMG submitted a review, later dismissed

2022-11-02 11:01 UTC, shvilaine approved these changes

2022-11-02 11:02 UTC, teddyandria approved these changes

2022-11-02 11:35 UTC, sblondeau requested changes
toujours les 2 images à enlever de assets/images

2022-11-02 11:38 UTC, toomanyMG approved these changes

2022-11-02 14:07 UTC, teddyandria approved these changes

2022-11-02 14:22 UTC, Zakari-B approved these changes

2022-11-02 14:23 UTC, merged