S01 us06 route table
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #74
Opened 2022-11-01 09:56 UTC by toomanyMG

J'ai essayer pleins de méthode différente que j'ai trouvé sur internet mais je n'arrive toujours pas à utiliser fill sur mes svg.

2022-11-01 10:37 UTC, williambouet approved these changes

2022-11-01 10:41 UTC, teddyandria approved these changes

2022-11-02 08:29 UTC, sblondeau requested changes

2022-11-02 08:29 UTC, sblondeau commented on src/Controller/ListRouteController.php
> +class ListRouteController extends AbstractController
Juste RouteController

2022-11-02 08:29 UTC, sblondeau commented on src/Controller/ListRouteController.php
> +    public function index()
ajoute des constantes
EASY_ROUTE = 1
MEDIUM_ROUTE = 2
DIFFICULT_ROUTE = 3
que tu manipuleras dans twig et dans ton controller plutot que d'utiliser directement les valeurs 1 2 et 3 (pas de "magic numbers")

2022-11-02 08:29 UTC, sblondeau commented on src/View/List/listRoute.html.twig
> +									{% if route.difficulty is same as 1 %}<img class="card-img icon-green"
et pour acceder à la constante depuis twig https://twig.symfony.com/doc/2.x/functions/constant.html

2022-11-02 08:34 UTC, teddyandria approved these changes

2022-11-02 09:27 UTC, closed without merging