S02 us22 admin delete members
WildCodeSchool/2022-09-php-orleans-project-papys45 pull request #94
Opened 2022-11-02 20:09 UTC by williambouet

2022-11-03 08:21 UTC, shvilaine submitted a review, later dismissed

2022-11-03 08:39 UTC, shvilaine submitted a review, later dismissed

2022-11-03 08:39 UTC, teddyandria submitted a review, later dismissed

2022-11-03 08:54 UTC, toomanyMG submitted a review, later dismissed

2022-11-03 10:26 UTC, shvilaine approved these changes

2022-11-03 10:37 UTC, toomanyMG approved these changes

2022-11-03 11:26 UTC, Zakari-B requested changes

2022-11-03 11:26 UTC, Zakari-B commented on src/Controller/AdminMemberController.php
> +            $idPhoto = $adminMembersManager->idPhoto((int) $id);
Pas de (int). En dessous non plus.

2022-11-04 04:31 UTC, toomanyMG approved these changes

2022-11-04 07:50 UTC, sblondeau requested changes

2022-11-04 07:50 UTC, sblondeau commented on src/Model/AdminMemberManager.php
>  class AdminMemberManager extends AbstractManager
non c'est juste un MemberManager, tu utilises le meme coté visiteur que coté admin, tu requetes sur la meme table

2022-11-04 07:50 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +            if (file_exists('upload/' . $idPhoto['photo'])) {
tu avais pas fais une constante pour le chemin vers upload ?

2022-11-04 07:50 UTC, sblondeau commented on src/View/Admin/members.html.twig
> +									<button type="button" class="btn btn-outline-warning btn-sm">Modifier</button>
non jamais de button dans un lien a, tu mets une classe btn sur le lien directement

2022-11-04 14:50 UTC, toomanyMG submitted a review, later dismissed

2022-11-04 14:50 UTC, shvilaine submitted a review, later dismissed

2022-11-04 15:10 UTC, shvilaine submitted a review, later dismissed

2022-11-04 15:10 UTC, toomanyMG approved these changes

2022-11-04 15:11 UTC, teddyandria approved these changes

2022-11-04 15:43 UTC, sblondeau requested changes

2022-11-04 15:43 UTC, sblondeau commented on src/Model/MemberManager.php
> +    public function idPhoto(int $id): array
pourquoi idPhoto ? alors que tu ne récupères meme pas l'id
le selectOneById de base n'est-il pas suffisant ?

2022-11-04 15:43 UTC, sblondeau commented on src/View/Admin/members.html.twig
> +					<button type="button" class="btn btn-danger align-self-right">Ajouter un membre</button>
grrrr

2022-11-04 15:43 UTC, sblondeau commented on src/View/Admin/members.html.twig
> +							<th scope="row">{{ member.id}}</th>
pas spécialement intéressant d'afficher l'id

2022-11-04 15:43 UTC, sblondeau commented on src/View/Admin/members.html.twig
> +</tbody></div></div></div>{% endfor %}</tbody></table></div></div></div> {% endblock %}
pb d'indentation ?

2022-11-04 15:43 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +            $adminMembersManager = new MemberManager();
$memberManager

2022-11-04 15:43 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +            header('Location:/admin/membres');
en bonus : un petit message "votre membre a bien été supprimé" via une query string

2022-11-04 20:42 UTC, williambouet commented on src/Model/MemberManager.php
> +    public function idPhoto(int $id): array
J'ai mis idPhoto pour 3 raisons : c'est la photo du membre (sa photo d'identité en quelque sorte), c'est une requête de pour récupérer la photo selon l'id et c'est une photo avec un id unique. 
J'appelle cette méthode lors de la suppression de la photo dans le serveur. Il me faut le nom exact de la photo avec son extension. Je croyais que c'était la façon la moins gourmande en donnée pour le faire.

2022-11-04 20:51 UTC, williambouet commented on src/View/Admin/members.html.twig
> +							<th scope="row">{{ member.id}}</th>
je sais, la seule utilitée que j'y trouvé c'est s'il y a 2 personnes ayant le même nom et prénom. Etant donné le contexte je supprime.

2022-11-07 13:01 UTC, toomanyMG submitted a review, later dismissed

2022-11-07 14:57 UTC, shvilaine submitted a review, later dismissed

2022-11-07 16:23 UTC, sblondeau requested changes

2022-11-07 16:23 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +        $membersManager = new MemberManager();
$memberManager

2022-11-07 16:23 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +            $membersManager = new MemberManager();
idem

2022-11-07 16:23 UTC, sblondeau commented on src/Model/MemberManager.php
> +    public function idPhoto(int $id): array
je ne vois tjs pas la plus value par rapport au selectOneById() que tu hérite de l'AbstractManager ? :-)

2022-11-08 10:16 UTC, teddyandria approved these changes

2022-11-08 10:19 UTC, toomanyMG approved these changes

2022-11-08 15:48 UTC, teddyandria approved these changes

2022-11-09 09:19 UTC, sblondeau approved these changes

2022-11-09 14:09 UTC, merged